[package]
name = "bs"
version = "0.1.0"
authors = ["Damian Gr√ºner <grunerdamian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.118", features = ["derive"]  }
bincode = "1.3.1"