[package]
name = "chann"
version = "0.1.0"
authors = ["Damian Gr√ºner <grunerdamian@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
spin_sleep = "1.0.0"